truncate table wp_ndic_request;

insert into wp_ndic_request
SELECT request_id,
    recipient_id,
    facility_id,
    request_date,
    first_name,
    middle_initial,
    last_name,
    suffix,
    spin,
    in_jail_flag,
    use_facility_address_flag,
    address_01,
    address_02,
    city,
    state,
    zip_code,
    phone,
    dorm,
    no_spiral_flag,
    in_touch_flag,
    prayer_request_flag,
    bible_request_flag,
    spanish_flag,
    no_devotional_flag,
    duplicate_flag,
    details,
    requesting_friend_id,
    deleted_flag,
    create_date,
    create_user_id,
    modify_date,
    modify_user_id
FROM ndic.import_request;
