DROP TABLE wp_ndic_request;

CREATE TABLE wp_ndic_request (
  request_id int(11) NOT NULL DEFAULT 0,
  recipient_id int(11) NOT NULL DEFAULT 0,
  address_id int(11) NOT NULL DEFAULT 0,
  request_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  first_name varchar(64) NOT NULL DEFAULT '',
  middle_initial char(5) NOT NULL DEFAULT '',
  last_name varchar(64) NOT NULL DEFAULT '',
  suffix varchar(64) DEFAULT NULL,
  spin varchar(64) DEFAULT NULL,
  in_jail_flag char(1) NOT NULL DEFAULT '',
  use_facility_address_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  address_01 varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  address_02 varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  city varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  state varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  zip_code varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  phone varchar(10) CHARACTER SET latin1 DEFAULT NULL,
  dorm varchar(128) CHARACTER SET latin1 DEFAULT NULL,
  no_spiral_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  in_touch_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  prayer_request_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  bible_request_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  spanish_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  no_devotional_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  duplicate_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'N',
  details text CHARACTER SET latin1 DEFAULT NULL,
  deleted_flag char(1) CHARACTER SET latin1 NOT NULL DEFAULT '',
  create_date datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  create_user_id int(11) NOT NULL DEFAULT 0,
  modify_date datetime DEFAULT NULL,
  modify_user_id int(11) DEFAULT NULL,
  PRIMARY KEY (request_id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
